server:
  port: 9998
#  ssl:
#    client-auth: none
#    enabled: true
#    key-store: C:/root/wx/www.0563repai.top.pfx
#    key-store-password: nlrfbtcy
#    key-store-type: PKCS12
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz97l2hlwpn29tj7uvo.mysql.rds.aliyuncs.com:3306/mall_app_rds?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true&nullCatalogMeansCurrent=true
    username: mall_rds
    password: Mall$%Rds+123

#security:
#  interceptor:
#    auth-paths: /api/shop/config/**
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  # redis:
#  profiles:
#    active: prod
#    host: localhost
#    port: 36379


wx:
  pay:
    merchants:
      # 商户1配置
      merchant1:
        merchantId: '1715243805'  # 商户号
        appId: 'wx70559cc67cdc94cc'  # 应用ID
        privateKeyPath: 'D:\code\mallapp\src\main\resources\wxCert\apiclient_key.pem'  # 商户私钥路径
        publicKeyPath: 'D:\code\mallapp\src\main\resources\wxCert\pub_key.pem'  # 微信支付公钥路径
        publicKeyId: 'PUB_KEY_ID_0117152438052025051500351948001800'  # 微信支付公钥ID
        merchantSerialNumber: '4145FC26AA94354CF3DB18870420E0E80AED7A82'  # 商户证书序列号
        apiV3Key: '7Uhb6ygv5tfc4rdx3esz2wa1q0pl9okm'  # API v3密钥
#        notifyUrl: 'http://mallapp.pdcspace.com/pay/v3/multi/callback/merchant1'  # 支付回调地址
        notifyUrl: 'http://j2c869a7.natappfree.cc/pay/v3/multi/callback/merchant1'  # 支付回调地址
  miniapp:
    app-id: wx1234567890abcdef  # 替换为你的小程序AppID
    app-secret: 1234567890abcdef1234567890abcdef  # 替换为你的小程序AppSecret
    token-expire-time: 604800  # token过期时间(秒)，7天

alipay:
  merchants:
    # 商户1配置
    merchant1:
      appId: '2021000148682383'  # 支付宝应用ID
      privateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCE3tJKl+WoWKnZilx43FzcU7yTJALcAaAQtpjyJVjdpqMJc+mgoaHH/NCUr5VxDMP70LTBRo0auDCwsfVd7Vdf5UMZguN7nLr4UNm6e0Pv8HwTwERtWU4vy/qizOOs7eEgQkX4xyTIDjB4Lc+ShI+56G0YHnaQ58bQeVjAdqIPnAOMrNKjarlznW/x97KNr2dbDLvi0sz/Kr/QE4zFwdVhByFWQGqgl8SMZ8cBdnWXbLKKgTDYzIUNsSNAqJM+LrLQfSedeJWNsU3L9jIO4wEabaLQq2vda2/FZcPgd4qaB2cs4cr0YW/rsV6mYtywDM0fObggO9iEHl539Nis4tVDAgMBAAECggEAYaulq72SzTg3yrjBlvptrGxFb2gGThFHx2FidoVrmKt4p2c0cqa91NOLw/B6CvsWSdI2POkOqniBGjIGqv/fvZc6xtMHQ4OHkSdllYYs/4CoxKAN7M+8ALiRygCQ0DqgxWTSKLjC2ehMSttp/UtCl6c6IoOqJoSqCe9ZhUjvgkbWd0uFtKRWIVjDd/gNPiHGWalNUbDsUem4d0ZPpTbymjiimmx/yRlMFWCFuV1rLDycugdgN9N9owegzMrMw1qJ7KoZpmkTunLnIFDmK3bjj4wUtjsVtB4V1NcPgyVsK2rw0LzmWE8oIXJfqtjnqii23iuS84wuJdX/86Pt+RLQyQKBgQDsQ/jq4HYbcl83lwIjlXuj9HWNUBNLCkKOq+mszlu6HQ5Rdm43vIramjFQxUk3soWBlPySflxkWEsN/r2IBm8xwZ2yMw53yLcIgh7EPxYTJWcybbQ5Qw7idvy6vKUwt694bHvuQbJ+Wu+IfTikNYDzZGGp5z2oaScRP1lDSwQKVQKBgQCP9/fDu2Yb0IUZRSMoDDxZG83BoxkMPMXUcyw2o7zwBQWAr3PwTGUZGUBNgm0v5iXPptgluwrBl1zkCu0U2IlHbVglyz3bB1RlzauLL3OTPX5XgUWvaS6UyI67JrJm42Ui9oGS7w13SxlfcMHBjqhZYIlDzB1QOmcSP6uueukpNwKBgBAi5FFGW0qsmQw26BJ+Fx+vhofMPEUXwkv0OdVvkpw3d87gg86StfkQJuYZU1LWgn/DKSzoLG8+CIJAL7mmltmTG64cBpTvxHB0Up2coWlVWKL9Ex4GEnItJj2qvK2DHhzfa+dt3T77/vgXdVLhxJja9kCgZnmmFOD8rqAF85SxAoGAALdVDi4yddT1tIh5gkt9SVwwC9SJ3Vu4CDSCdcset3ru6hL1Wq6mmhdcEIajkGdurLfBv35MsWXVWnULdN0W4boThCycpChHLTJ2tfyIcKUPqdPEyviU+Lx+qUOqA4UCDch4IIj74ioHeEgRTqss/zTRufqb8rg3pwmWCwolesUCgYEAx1i+K1C2bg4p8cudy50hKA3lKExZV3esiQWTGO0+jJuFZaynbDMorvcXqntnPx6TIqYrMWZ1OFNGo3tRG03/7bLKz58762J5afKgeghypWouvGkpKrbH6vKwuQfFdVI0jolQyXgLDlQ4U/2ukw7H/VO7xxf6pq9TFQMCiHnV9wQ="    # 商户私钥，以 MII 开头的 PKCS8 格式私钥
      publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAko47xPKaS0mcpHNJTKBsZUA02BRpRLMNctmdqbjjMNoChzUYgEM0qcH1fBsz2GUPNRycwMbNsNIP+DXC8k7T86epc7tA1ezkmYWKM93B49M3C2cWYXg+xBB+9yJCyeiTHMan6MPdGtERQgpu97nAtCDmqLR6plHN7rr+D3WRup1LzmrAiAx2ywbzpRabFe9eCwECd2kXKzxPvkTXhO2JItN0hVnpXrOmtuyVxlBrmjVEZRvZlPzPHOvTYBRHOdxEyANvno1lKI4Z8ZlbZ5LO8lPSY5MZqvEipLV0OdWsXdDuKMJsN6+ne8TvMlVh0VpHl0rTpDpOTJIk5nX+9RUn6QIDAQAB"     # 支付宝公钥
      notifyUrl: 'http://j2c869a7.natappfree.cc/pay/v3/alipay/notify/merchant1'  # 异步通知地址
      returnUrl: 'http://j2c869a7.natappfree.cc/pay/v3/alipay/return/merchant1'  # 同步返回地址
      signType: 'RSA2'  # 签名方式，默认RSA2
      charset: 'UTF-8'  # 字符编码，默认UTF-8
      format: 'json'    # 返回格式，默认json
      sandboxMode: true  # 是否使用沙箱环境


#wx:
#  pay:
#    #微信公众号或者小程序等的appid (V3商户模式需要)
#    # appId: wx563d55bfb846c2ed
#    appId: wx70559cc67cdc94cc
#    # appsecret
#    #b5e034741bb55248b9d7c4decf2e28a6
#    #微信支付商户号 (V3商户模式需要)
#    mchId: 1715243805
#    #微信支付商户密钥
##    mchKey: 131jsjdf9iwe31rew2r
#    #    subAppId: #服务商模式下的子商户公众账号ID
#    #    subMchId: #服务商模式下的子商户号
#    # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
#    keyPath: classpath:wxCert/apiclient_cert.p12
#    # apiKey: 7Uhb6ygv5tfc4rdx3esz2wa1q0pl9ok2
#    # apiV3 秘钥值 (V3商户模式需要)
#    apiV3Key: 7Uhb6ygv5tfc4rdx3esz2wa1q0pl9okm
#    # apiV3 证书序列号值 (V3商户模式需要)
##    certSerialNo: 4145FC26AA94354CF3DB18870420E0E80AED7A82
#    certSerialNo: 4145FC26AA94354CF3DB18870420E0E80AED7A82
#    # apiclient_cert.pem证书文件的绝对路径或者以classpath:开头的类路径. (V3商户模式需要)
#    privateCertPath: classpath:wxCert/apiclient_cert.pem
#    # apiclient_key.pem证书文件的绝对路径或者以classpath:开头的类路径. (V3商户模式需要)
#    privateKeyPath: classpath:wxCert/apiclient_key.pem
#    # 微信支付公钥，pub_key.pem证书文件的绝对路径或者以classpath:开头的类路径. (V3商户模式需要)
#    publicKeyPath: classpath:wxCert/pub_key.pem
#    # 微信支付公钥ID (V3商户模式需要)
#    publicKeyId: PUB_KEY_ID_0117152438052025051500351948001800
##    mchKey: 68EE48914BD37392C6E2320FD07DAD71FD61F69F
##    public-key-path: classpath:wxCert/wechatpay_68EE48914BD37392C6E2320FD07DAD71FD61F69F.pem


logging:
  level:
    org.springframework.web: info
    com.github.binarywang.demo.wx.pay: debug
    com.github.binarywang.wxpay: debug


#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/miniapp?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    database: 0
#    timeout: 3000

